### ISSUE TITLE
I made a fork with SPI support and some refactorings... not sure what next

### ISSUE THREAD

**Issue by afiskon** [4ilo/ssd1306-stm32HAL#2]
Hello Oliver,

First of all, thank you so much for sharing this library! It was exactly what I was looking for and it worked flawlessly.

I wanted to make you know that I made a fork of your library:

https://github.com/afiskon/stm32-ssd1306

I refactored the code a bit (e.g. all library files are in one directory now, and examples are in other directories), implemented some minor features I needed (e.g. mirroring support) and most importantly - my fork supports 4-wire SPI protocol.

I was hoping perhaps we could somehow merge our libraries. The problem is - I'm not sure how. The structure differs quote a lot so I can't simply send a pull request. Would you be interested in moving my code to your repository entirely? Or maybe vice versa - closing your repository with redirect to mine? Or maybe you wold be interested in just mentioning my fork in README.md of your library so people could easily find it if they need SPI support?

What do you think?

**Comment by 4ilo** [comment]
Great work! 
I will place a link to your repository in my readme file.

Thanks for the contribution.

**Comment by afiskon** [comment]
Thank you very much!
