### ISSUE TITLE
Custom Font , 

### ISSUE THREAD

**Issue by gc9n** [4ilo/ssd1306-stm32HAL#4]
Hey hello there, 

I need to import a specific font , do you have a converter in order to import my fonts?

**Comment by 4ilo** [comment]
No i dont, if you need a custom font, you will need to convert it yourself into the format as provided in
the [fonts](https://github.com/4ilo/ssd1306-stm32HAL/blob/master/Src/fonts.c) file.

**Comment by gc9n** [comment]
how you made the font files ?

**Comment by gc9n** [comment]
Really now , can you please tell me how you import the fonts?

**Comment by 4ilo** [comment]
I did not make the font files, just found them on the internet.

**Comment by MUDAL** [comment]
Hello @4ilo, can you remember where you found the font files on the internet? A link will be greatly appreciated. Thanks for developing this fantastic library
