### ISSUE TITLE
Vertical interlacing and correct screen size setup

### ISSUE THREAD

**Issue by Vavat** [4ilo/ssd1306-stm32HAL#7]
With some 128x32 displays default settings don't work and need to be adjusted:
- [Line 43 of ssd1306.c](https://github.com/4ilo/ssd1306-stm32HAL/blob/4674b0a6244ae184f2bb88d660d6c6caa7c9f5df/lib/ssd1306.c#L43) has to be modified according to the size of the screen that is used. Specifically, number of horizontal lines.
- [Line 52 of ssd1306.c](https://github.com/4ilo/ssd1306-stm32HAL/blob/4674b0a6244ae184f2bb88d660d6c6caa7c9f5df/lib/ssd1306.c#L52) has to be modified depending on exact manufacturing method of 32 line displays. It seems that some manufacturers do one to one mapping of 32 lines to 32 pins and leave 32 to 63 unused, while some interlace, so mapping becomes 0 to 0, 1 to 2, 2 to 4, 3 to 6, etc. This type of mapping can be taken into account by flipping bit 5 of command 0xDA. 
Which way specific screen is manufactured is impossible to know, so it has to be tested. Adjustment is trivial, however.
@4ilo, if you'd like me to submit a branch to propose a fix for this issue, assign it to me.

P.S. I've emailed you about it earlier, but you can ignore that email now that I found the source of the problem.

**Comment by 4ilo** [comment]
Based on your investigation i made some changes. However i do not have access to a 128x32 oled screen myself, can you test the changes in #8 and let me know if they solve your problem? If the changes are validated i will merge them in the master branch.

**Comment by 4ilo** [comment]
Implemented in #8.
